server:
  port: 7100
  servlet:
    context-path: /

spring:
  profiles:
    active: develop

  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  activiti:
    check-process-definitions: false
    database-schema-update: true
    history-level: full
mybatis:
  type-aliases-package: com.hsbc.activity.module.**.model
    #映射文件路径
  mapper-locations: classpath:mapper/*.xml


# logback配置文件
logging:
  config: classpath:logback-spring.xml

