spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.49.174:3306/activity?characterEncoding=utf-8&useSSL=false
    username: root
    password: 'GuoCui1110'
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false

